'12':
  top_left  : [213, 134]
  top_right : [213, 134]
  bot_right : [213, 134]
  bot_left  : [213, 134]
  place     : ['end', 'start']
  pad       : [200, 200]
  scale     : [668, 100]
'218':
  top_left  : [394, 977]
  top_right : [1075, 406]
  bot_right : [292, 130]
  bot_left  : [31, 261]
  place     : ['end', 'start']
  pad       : [350, 120]
  scale     : [534, 206]
'219':
  top_left  : [80,  277]
  top_right : [684, 821]
  bot_right : [1009, 191]
  bot_left  : [563, 99 ]
  place     : ['end', 'end']
  pad       : [200, 150]
  scale     : [534, 387]
'220':
  top_left  : [12, 252]
  top_right : [769, 538] # [890, 583]  # [866, 622]
  bot_right : [841, 143] # [976, 164]  # [994, 167]
  bot_left  : [406, 105]
  place     : ['end', 'start']
  pad       : [0, 100]
  scale     : [448, 387]
'221':
  top_left  : [608 , 886]
  top_right : [1079, 324]
  bot_right : [426 , 102 ]
  bot_left  : [20  , 252]
  place     : ['end', 'start']
  pad       : [250 , 150]
  scale     : [618, 387]